name: Build Test
on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      was_updated: ${{ steps.check-change.outputs.change_detected }}
      check_commit: ${{ steps.check-changelog.outputs.check_commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Extract changelog info
        # if: steps.check-changelog.outputs.check_commit == 'false'
        id: extract-changelog
        run: |
          # Encode PR description to base64 and then decode it to a temporary file
          echo "${{ github.event.pull_request.body }}" | base64 | base64 -d > /tmp/pr_description.txt
          # Saving template content to another temporary file
          cat .github/pull_request_template.md > /tmp/template_content.txt
          echo ".github/pull_request_template.md > /tmp/template_content.txt"
      
          # Using diff to compare files. If they're the same, then we output an error.
          echo "PR............... /tmp/pr_description.txt"
          echo "template     /tmp/template_content.txt"
          if diff -q /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
            echo "ERROR: PR description is identical to the template"
            exit 1
          fi
      










