name: Build Test
on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update-changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      was_updated: ${{ steps.check-change.outputs.change_detected }}
      check_commit: ${{ steps.check-changelog.outputs.check_commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0
          
      - name: Extract changelog info
        # if: steps.check-changelog.outputs.check_commit == 'false'
        id: extract-changelog
        run: |
         PR_DESCRIPTION="${{ github.event.pull_request.body }}"
         echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
         echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
         cat /tmp/pr_description.txt
        
         # Save the template content to a file
         TEMPLATE_CONTENT="$(cat .github/pull_request_template.md)"
         echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
         echo "Template content saved to /tmp/template_content.txt."
         cat /tmp/template_content.txt
        
         # Use diff to compare the two files
         if diff -wB /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
             echo "ERROR: PR description is identical to the template."
             exit 1
         else
             echo "PR description and template are different."
         fi










