name: Lint TypeScript Code

on:
  push:
    paths:
      - '**.ts'
  pull_request:
    paths:
      - '**.ts'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gha-utilities/eslint-action@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          eslint-args: '**/*.ts'
