name: PR Content Check
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compare-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare PR description to template
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          TEMPLATE_CONTENT=$(cat .github/workflows/template.md)
          chmod +x .github/workflows/compare_contents.sh
          .github/workflows/compare_contents.sh "$PR_DESCRIPTION" "$TEMPLATE_CONTENT"
