name: Test
on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  

  update-changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      was_updated: ${{ steps.check-change.outputs.change_detected }}
      check_commit: ${{ steps.check-changelog.outputs.check_commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check for updated CHANGELOG.md using git
        id: check-changelog
        run: |
          echo "${{ github.event.pull_request.body }}" > /tmp/pr_description.txt

      - name: Save template content
        run: |
          cat .github/workflows/pull_request_template.md > /tmp/template_content.txt
  
      - name: Compare PR description and template
        run: |
          if diff -wB /tmp/pr_description.txt /tmp/template_content.txt; then
            echo "PR description and template are different"
          else
            echo "ERROR: PR description is identical to the template"
            exit 1
          fi
