name: test

on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
     - name: Fetch and Sanitize PR description
       run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          # Safely print the PR description using Node.js
          node -e 'const prDesc = process.argv[1]; console.log(prDesc);' "$PR_DESCRIPTION"

      
  
