name: Lint TypeScript

on:
  push:
    paths:
    - '**.ts'
  pull_request:
    paths:
    - '**.ts'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'  # Adjust this based on your project's requirements

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint on TypeScript files
      run: npx eslint '**/*.ts' --max-warnings=0

