name: PR Content Check
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  compare-contents:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compare PR description to template
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          TEMPLATE_CONTENT=$(cat .github/workflows/pull_request_template.md)

          # Normalize content: strip newlines, leading and trailing whitespaces
          NORMALIZED_PR=$(echo "$PR_DESCRIPTION" | tr -d '\n' | tr -d ' ' | tr -d '\t')
          NORMALIZED_TEMPLATE=$(echo "$TEMPLATE_CONTENT" | tr -d '\n' | tr -d ' ' | tr -d '\t')

          if [ "$NORMALIZED_PR" == "$NORMALIZED_TEMPLATE" ]; then
            echo "ERROR: PR description is identical to the template."
            exit 1
          fi
