name: Test
on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  

  update-changelog:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      was_updated: ${{ steps.check-change.outputs.change_detected }}
      check_commit: ${{ steps.check-changelog.outputs.check_commit }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Check for updated CHANGELOG.md using git
        id: check-changelog
        run: |
          if git diff --name-only origin/${{ github.base_ref }} | grep -q "^CHANGELOG.md$"; then
            echo "CHANGELOG.md has been updated."
            echo "::set-output name=check_commit::true"
          else
            echo "ERROR: CHANGELOG.md has not been updated."
            echo "::set-output name=check_commit::false"
          fi
      - name: Extract changelog info
        if: steps.check-changelog.outputs.check_commit == 'false'
        id: extract-changelog
        run: |
          PR_DESCRIPTION="${{ github.event.pull_request.body }}"
          TEMPLATE_CONTENT=$(cat .github/workflows/pull_request_template.md)
          
          # Write to temporary files
          echo "$PR_DESCRIPTION" > /tmp/pr_desc.txt
          echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
          
          # Use diff to compare, ignoring whitespace and blank lines
          DIFF_OUTPUT=$(diff -wB /tmp/pr_desc.txt /tmp/template_content.txt)

          # Check diff output
          if [ -z "$DIFF_OUTPUT" ]; then
              echo "PR description is identical to pull_request_template.md"
              exit 1
          else
              echo "PR description differs from pull_request_template.md"
              echo "Differences:"
              echo "$DIFF_OUTPUT"
          fi
