name: Lint Check

on:
  push:
    branches:
      - main  # Change this to match your main branch
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up ShellCheck for .sh files
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Lint .sh files
      run: find . -type f -name "*.sh" -exec shellcheck {} \;

    - name: Set up ESLint for .js files
      run: npm install eslint eslint-plugin-header

    - name: Lint .js files
      run: eslint --ext .js .

    - name: Set up dos2unix for .bat files
      run: sudo apt-get install -y dos2unix

    - name: Lint .bat files
      run: find . -type f -name "*.bat" -exec dos2unix -k {} \;
