name: Lint Check

on:
  push:
    branches:
      - main  # Change this to match your main branch
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck

    - name: Lint .sh files
      run: |
        for file in $(find . -name "*.sh"); do
          shellcheck "$file" || { echo "Linting errors found in $file"; exit 1; }
        done
