name: test

on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Compare PR description with template
      env:
        PR_DESCRIPTION: ${{ github.event.pull_request.body }}
      run: |
        # Safely print the PR description using Node.js
        node -e 'const prDesc = process.env.PR_DESCRIPTION; console.log(prDesc);'
    
        echo "$PR_DESCRIPTION" > /tmp/pr_description.txt
        echo "PR DESCRIPTION saved to /tmp/pr_description.txt."
            
        # Save the template content to a file
        TEMPLATE_CONTENT=$(sed 's/"//g' .github/pull_request_template.md)
        echo "$TEMPLATE_CONTENT" > /tmp/template_content.txt
        echo "Template content saved to /tmp/template_content.txt."
            
        # Use diff to compare the two files
        if diff -wB /tmp/pr_description.txt /tmp/template_content.txt > /dev/null; then
          echo "ERROR: PR description is identical to the template."
          exit 1
        else
          echo "PR description and template are different."
        fi


      
  
