name: "File existence check"

on: [push, pull_request]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: copy-repo

      - name: echo
        run: ls -lart
      
      - name: echo
        run: ls -lart copy-repo

      - name: Get changed files
        id: changed-files
        run: |
            if ${{ github.event_name == 'pull_request' }}; then
                echo "changed_files=$(git diff --name-only -r HEAD^1 HEAD | xargs)" >> $GITHUB_OUTPUT
            else
                echo "changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)" >> $GITHUB_OUTPUT
            fi

      - name: Check if CHANGELOG is added
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            doc:
              - copy-repo/CHANGELOG.md

      - name: Abort the workflow if CHANGELOG is not updated
        if: steps.changed-files-yaml.outputs.doc_any_changed != 'true'
        run: |
          echo "CHANGELOG not added. Please add the CHANGELOG in CHANGELOG.md file"
          exit 1
        
  Build:
    runs-on: ubuntu-latest
    needs: check_changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
