name: test

on:
  push:
    branches:
      - v2.x/staging
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch and Sanitize PR description
      run: |
        PR_BODY=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
          jq -r .body)
        SANITIZED_PR_DESCRIPTION=$(echo "$PR_BODY" | sed "s/\`/[BT]/g")
        echo "$SANITIZED_PR_DESCRIPTION" > /tmp/pr_description.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

