name: "File existence check"

on: [push, pull_request]

jobs:
  check_changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          path: copy-repo

      - name: Check if CHANGELOG is added
        id: changed-files-yaml
        uses: tj-actions/changed-files@v37
        with:
          files_yaml: |
            doc:
              - copy-repo/CHANGELOG.md

      - name: Abort the workflow if CHANGELOG is not updated
        if: steps.changed-files-yaml.outputs.doc_any_changed != 'true'
        run: |
          echo "CHANGELOG not added. Please add the CHANGELOG in CHANGELOG.md file"
          exit 1
        
  Build:
    runs-on: ubuntu-latest
    needs: check_changelog
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
