name: Lint TypeScript

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ShellCheck for .sh files
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Set up dos2unix for .bat files
        run: sudo apt-get install -y dos2unix

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Lint TypeScript
        run: npm run lint:sh
